spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tresmoto
    username: root
    password: abhi@Nov11
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    open-in-view: false

server:
  port: 9090
  servlet:
    contextPath: /tresmoto/api/v1
  http2:
    enabled: true
  tomcat:
    max-threads: 200